spring.application.name: demo

spring.ai.azure.openai:
  chat.options:
    deployment-name: gpt-35-turbo
    model: gpt-35-turbo
    temperature: 0.7
  api-key: api-key-placeholder
  endpoint: https://openaidemo001.openai.azure.com/